### ISSUE TITLE
perm device mount point

### ISSUE THREAD

**Issue by ptdropper** [LairdCP/wb-buildroot#4]
Testing the /perm mount shows errors at boot up. The directories /perm/etc and /perm/log cannot be created at boot time. 
I found that an edit to pre-systemd-init.sh corrects it for me by changing the value of "PERM_DEVICE" from "ubi0_6" to the value "/dev/ubi0_5", example:

PERM_DEVICE=/dev/ubi0_5

Then the boot is clean, no issues from the init script creating the /perm/etc and /perm/log directories.

**Comment by borkra** [comment]
Ignore errors for /perm,  they are not real, systemd cannot create the partitions because they already have been created before systemd started. Thus you get the error.

We have to create directories before systemd starts,  because systemd itself does not create them early enough. But we have to keep creation code in systemd scripts so it can put stuff where it belongs. So just ignore the errors, it’s just work arounds for system quirks.

I will close this.

**Comment by borkra** [comment]
It looks like you are not using latest software this area changed a lot.

**Comment by ptdropper** [comment]
Moved to latest no issues.
